### ISSUE TITLE
No sync in brave

### ISSUE THREAD

**Issue by vvzvlad** [T3aHat/DeepLopener#13]
Hello, I am using brave as a substitute for chrome (it is the same, only without google services), and it also has synchronization functionality, but in the translator extension the api key is not saved after exiting the settings. Can you tell me what to do in my case?

**Comment by Kesk0** [comment]
kinda same.

**Comment by T3aHat** [comment]
Thank you for your comments and sorry for the late reply.

I was able to reproduce this problem myself and found out that this is caused by the `chrome.identity` in the extension code not working properly in Brave.
This code is used to protect your API_KEY, so it is difficult to change the implementation at this time.
If you want to use it now, please use Chrome, which is the recommended environment, sorry.

If there are more requests to fix it (and my free time), I may re-implement in the future.
I will report any good news here in the future.

**Comment by vvzvlad** [comment]
I don't really understand why I need to protect API_KEY at all. I'm not really worried about someone being able to use my free translation service key, and even if they can, all they can take away from me is a 5000 (or whatever the free account provides) word translation. 
It seems to me that just adding a "don't protect my key" option would be enough of a fix.

**Comment by jasonblack1027** [comment]
> 

I also agree.

**Comment by T3aHat** [comment]
I have addressed this issue today 5a1f3cfee47b6cbf57605470e4f9e42030d6dda6 .
If you get an error after update, please try uninstalling and reinstalling.
The ChromeWebStore will be getting an update soon.
If `chrome.identity` is not available, you can now use this extension without obfuscation of API_KEY.
However, developers are strongly encouraged to use it with synchronization.

**Comment by vvzvlad** [comment]
Yes, I confirm that saving the key works in Brave. Thank you!
