### ISSUE TITLE
Add the ability to translate a page

### ISSUE THREAD

**Issue by Zero3K** [T3aHat/DeepLopener#3]
It would be nice if it could translate an entire page (and if possible, offer an automatic translation option).

**Comment by T3aHat** [comment]
I'd like to have that feature too.
However, my current implementation opens a large number of tabs and puts too much load on DeepL at once. This is really bad.
Alternatively, I came up with a way to combine the entire page strings into a single request and split the returned translation locally. But I'm not going to implement this because I'm not good enough.

**Comment by Zero3K** [comment]
You can add a help wanted label to this issue.

**Comment by T3aHat** [comment]
I implemented an entire page translatable extension [DeepLopener_PRO](https://github.com/T3aHat/DeepLopener_PRO).
